---
- name: Set server hosts fact
  ansible.builtin.set_fact:
    k3s_server_hosts: "{{ groups['server'] }}"
  run_once: true

- name: Set high availability cluster fact
  ansible.builtin.set_fact:
    k3s_ha_cluster: '{{ k3s_server_hosts | length > 2 }}'
  run_once: true

- name: Set non high availability cluster fact
  ansible.builtin.set_fact:
    k3s_non_ha_cluster: '{{ k3s_server_hosts | length == 1 }}'
  run_once: true

- name: Set server ips fact
  ansible.builtin.set_fact:
    k3s_server_ips: "{{ k3s_server_hosts | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
  when: ansible_host in k3s_server_hosts

- name: Set server default host fact
  ansible.builtin.set_fact:
    k3s_server_default_host: "{{ hostvars[k3s_server_hosts[0]]['ansible_fqdn'] | default(k3s_server_hosts[0]) }}"
  run_once: true

- name: Set server default ip fact
  ansible.builtin.set_fact:
    k3s_server_default_ip: '{{ ansible_default_ipv4.address }}'
  when: ansible_host in k3s_server_hosts

- name: Set service type fact
  ansible.builtin.set_fact:
    k3s_service_type: "{{ 'agent' if ansible_host not in k3s_server_hosts else 'server' }}"

- name: Set token fact
  ansible.builtin.set_fact:
    k3s_token: "{{ hostvars[k3s_server_default_host]['token'] | default('') }}"
  run_once: true

- name: Set variables fact
  ansible.builtin.set_fact:
    k3s_vars: '{{ k3s_vars }}'
  run_once: true